### ISSUE TITLE
Create a v13.x maintenance branch with a 13.5 build supporting openssl3

### ISSUE THREAD

**Issue by akrherz** [conda-forge/postgresql-feedstock#112]
Issue
-------

Presently within conda-forge, there is no libpq=13 + openssl3 build.  There are some dependency combinations, like what I am finding in conda-forge/gdal-feedstock#590 that could use such a combination.

The [Postgresql 13.5 Release Notes](https://www.postgresql.org/docs/release/13.5/) indicate openssl3 support was added with that point release.

Proposal
------------
I'd like to create a `v13.x` maintenance branch with a 13.5 release and run the openssl3 migration with it.

I'm happy to do all the work here, just would need for somebody to kindly review the PRs...

Thanks for the consideration.

**Comment by ocefpaf** [comment]
I'm happy to review them. Can't promise to help much more than that though. sorry.

**Comment by akrherz** [comment]
Completed, thanks.
