### ISSUE TITLE
Please compile with readline support

### ISSUE THREAD

**Issue by akrherz** [conda-forge/postgresql-feedstock#13]
I am thankful for the efforts made to provide postgresql for conda, but not having readline support make usage of `psql` not much fun :(  I assume there is a valid reason for not including it, so am curious about it.  Seems like readline is in conda already?

**Comment by mariusvniekerk** [comment]
Pull requests are welcome

**Comment by ocefpaf** [comment]
> I assume there is a valid reason for not including

I don't really recall if there is a reason. @msarahan do you know if there is a reason to not use `readline`?
