### ISSUE TITLE
Build postgresql-contrib package

### ISSUE THREAD

**Issue by sodre** [conda-forge/postgresql-feedstock#15]
I really appreciate having postgresql available through conda. It makes it really easy during tests and in some cases deployment.

Would it be possible to build the contrib section as well? There quite a few extensions that I would like to use.

**Comment by mariusvniekerk** [comment]
That may be better as an additional feedstock perhaps?

**Comment by ocefpaf** [comment]
> That may be better as an additional feedstock perhaps?

I don't really know what `postgresql-contrib` is but, if that comes from the same source as `postgresql` we can use conda's `outputs` section to have two packages derived from the same recipe.

**Comment by mariusvniekerk** [comment]
Particularly if we start thinking about postgis

**Comment by mariusvniekerk** [comment]
Does conda forge support the new outputs portion?

**Comment by ocefpaf** [comment]
> Does conda forge support the new outputs portion?

We may find a few hiccups, like hitting a timeout for certain feedstocks, but in general that is the direction we want to go.

**Comment by sodre** [comment]
Awesome, I'll propose a patch using the outputs section. 

I also have a separate PR ready to submit for postgis.

**Comment by sodre** [comment]
Issue fixed with PRs #19 and conda-forge/staged-recipes#5073

**Comment by sodre** [comment]
When we merged #28 we lost the contrib section. Things are a little strange because we are still calling `make -C contrib install` in the build.sh file, but the result of that install is not making into any of the packages. 

I verified that in 10.4 the compiled extensions were being installed and in 10.5 (post #28) they are no longer there.
