### ISSUE TITLE
OpenSSL 3.2 breaks postgres

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/postgresql-feedstock#178]
The recent release of OpenSSL 3.2.0 has surfaced some latent problems with postgres, which are in the process of being fixed (there's an in-progress [discussion](https://www.postgresql.org/message-id/CX9SU44GH3P4.17X6ZZUJ5D40N%40neon.tech), plus a draft patch available).

We probably need to repodatapatch all existing builds to use `openssl <3.2`. Going forward, we can either add that cap (until the patch is merged and released) or backport the patch.

PS. Upstream OpenSSL commented:
> Bottom line: Postgres BIO API misuse that finally broke in practice. Not related to this [issue](https://github.com/openssl/openssl/pull/22820/files).

Xref:
https://github.com/conda-forge/openssl-feedstock/issues/144
https://github.com/Homebrew/homebrew-core/issues/155651

CC @conda-forge/postgresql

**Comment by hmaarrfk** [comment]
Lets create a new release that has the correct pin? Then we can merge the repodata patch?

**Comment by h-vetinari** [comment]
The two steps are independent from each other (except that we shouldn't merge new PRs here unless they add either the patch or the cap)

**Comment by hmaarrfk** [comment]
> except that we shouldn't merge new PRs here unless 

Right, so i prefer to avoid future failures where we can.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by h-vetinari** [comment]
> Right, so i prefer to avoid future failures where we can.

With you on that, though my preference (not strongly held) would have been to fix the repodata (to stop the bleeding), but wait a bit if the upstream patch materialises before doing something on this feedstock.

In any case, fine with me to add the cap right away.

**Comment by hmaarrfk** [comment]
if i weren't willing to do it, i would let it slide. please see suggested PR #179  now that I've made it, I'm more happy to merge to stop the bleeding, so long as there is an established path to "updating" this feedstock
