### ISSUE TITLE
Unpin libxml2

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/postgresql-feedstock#183]
### Comment:

In https://github.com/conda-forge/postgresql-feedstock/pull/182 and https://github.com/conda-forge/postgresql-feedstock/pull/181

openssl 3.2 compatibility was fixed but libxml2 was pinned

we should work to unpin it.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by akrherz** [comment]
@hmaarrfk , it was pinned due to unknown problems on OSX pulling in libxml2, has something been fixed upstream within build infra?

**Comment by hmaarrfk** [comment]
is there an issue you can cross reference?

**Comment by akrherz** [comment]
> is there an issue you can cross reference?

No, I just thought it was a "known problem" when the dep solver sometimes makes bad life choices.  I saw a conda-forge admin do this pinning trick in some other repo to workaround a problem like what shown up with this repo.

**Comment by h-vetinari** [comment]
Now that #201 / #200 was merged, I think we should remove the dual pin again (i.e. revert https://github.com/conda-forge/postgresql-feedstock/commit/328a9e2ac2b3c3046971f9c6a46abb8cab53b262).
