### ISSUE TITLE
.src_tree?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/postgresql-feedstock#57]
Appears there is some (broken?) submodule `.src_tree` in the feedstock. Should this be here? If so, should it be fixed somehow? If not, could it be dropped?

**Comment by jakirkham** [comment]
@conda-forge/postgresql, thoughts? 🙂

**Comment by akrherz** [comment]
@jakirkham good question.  I can't imagine this being used.  I wonder what the "best way" is to delete it...
